### Bellevue University
### DSC-540 Data Preparation
### Name: Tai Ngo
### Date: 5/3/2020

### Week 7 & 8 Exercises

In [379]:
# Load required libraries
import pandas as pd
import numpy as np

In [380]:
# Load the data into a dataframe
# use "Candy Hierarchy 2015 Survey Response" file for the data
df = pd.read_excel('CANDY-HIERARCHY-2015-SURVEY-Responses.xlsx')
df.head(7)

,Timestamp,How old are you?,Are you going actually going trick or treating yourself?,[Butterfinger],[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers],[Bottle Caps],...,[Necco Wafers],"Which day do you prefer, Friday or Sunday?",Please estimate the degrees of separation you have from the following folks [Bruce Lee],Please estimate the degrees of separation you have from the following folks [JK Rowling],Please estimate the degrees of separation you have from the following folks [Malala Yousafzai],Please estimate the degrees of separation you have from the following folks [Thom Yorke],Please estimate the degrees of separation you have from the following folks [JJ Abrams],Please estimate the degrees of separation you have from the following folks [Hillary Clinton],Please estimate the degrees of separation you have from the following folks [Donald Trump],Please estimate the degrees of separation you have from the following folks [Beyoncé Knowles]
0,2015-10-23 08:46:20.451,35,No,JOY,NaN,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-10-23 08:46:51.583,41,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-10-23 08:47:34.285,33,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-10-23 08:47:58.964,31,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-10-23 08:48:11.719,30,No,NaN,JOY,DESPAIR,JOY,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015-10-23 08:49:06.808,38,No,JOY,JOY,DESPAIR,JOY,DESPAIR,JOY,JOY,...,JOY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015-10-23 08:50:08.918,48,No,JOY,JOY,DESPAIR,JOY,JOY,DESPAIR,JOY,...,DESPAIR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### At a quick glimpse at the first few rows, the 4th row has a missing data on the Butterfinger column.

### 1. Filter out missing data

In [381]:
# check the columns
df.columns

Index(['Timestamp', 'How old are you?',
       'Are you going actually going trick or treating yourself?',
       ' [Butterfinger]', ' [100 Grand Bar]',
       ' [Anonymous brown globs that come in black and orange wrappers]',
       ' [Any full-sized candy bar]', ' [Black Jacks]', ' [Bonkers]',
       ' [Bottle Caps]',
       ...
       ' [Necco Wafers]', 'Which day do you prefer, Friday or Sunday?',
       'Please estimate the degrees of separation you have from the following folks [Bruce Lee]',
       'Please estimate the degrees of separation you have from the following folks [JK Rowling]',
       'Please estimate the degrees of separation you have from the following folks [Malala Yousafzai]',
       'Please estimate the degrees of separation you have from the following folks [Thom Yorke]',
       'Please estimate the degrees of separation you have from the following folks [JJ Abrams]',
       'Please estimate the degrees of separation you have from the following folks [Hillary Clinton]',
       'Please estimate the degrees of separation you have from the following folks [Donald Trump]',
       'Please estimate the degrees of separation you have from the following folks [Beyoncé Knowles]'],
      dtype='object', length=124)

In [382]:
# drop all columns that have only missing data, as long as the columns have some values, they will be kept
df_1 = df.dropna(axis=1, how='all')
df_1

,Timestamp,How old are you?,Are you going actually going trick or treating yourself?,[Butterfinger],[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers],[Bottle Caps],...,"Fill in the blank: ""Imitation is a form of ____________""",Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"[Sea-salt flavored stuff, probably chocolate, since this is the ""it"" flavor of the year]",[Necco Wafers],"Which day do you prefer, Friday or Sunday?"
0,2015-10-23 08:46:20.451,35,No,JOY,NaN,DESPAIR,JOY,NaN,NaN,NaN,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,1,NaN,NaN,NaN
1,2015-10-23 08:46:51.583,41,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,Laziness,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,JOY,DESPAIR,NaN
2,2015-10-23 08:47:34.285,33,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,JOY,DESPAIR,NaN
3,2015-10-23 08:47:58.964,31,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,JOY,DESPAIR,NaN
4,2015-10-23 08:48:11.719,30,No,NaN,JOY,DESPAIR,JOY,NaN,NaN,NaN,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,2015-10-31 05:23:40.526,50,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,Flattery,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,DESPAIR,DESPAIR,Friday
5626,2015-10-31 05:29:26.937,43,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Flattery,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,DESPAIR,DESPAIR,Sunday
5627,2015-10-31 06:13:29.083,35,Yes,NaN,JOY,DESPAIR,JOY,NaN,NaN,DESPAIR,...,Flattery,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,NaN,NaN,Friday
5628,2015-10-31 06:26:52.566,38,No,JOY,JOY,JOY,JOY,JOY,JOY,JOY,...,Lazily flattering someone,2,1,3 or higher,3 or higher,1,3 or higher,JOY,JOY,Sunday
5629,2015-10-31 06:41:31.904,44,No,DESPAIR,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,Flattery,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,DESPAIR,JOY,Friday

In [383]:
# drop only rows with missing data, no columns or rows will have a missing value
df_1 = df_1.dropna()
df_1

,Timestamp,How old are you?,Are you going actually going trick or treating yourself?,[Butterfinger],[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],[Bonkers],[Bottle Caps],...,"Fill in the blank: ""Imitation is a form of ____________""",Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"[Sea-salt flavored stuff, probably chocolate, since this is the ""it"" flavor of the year]",[Necco Wafers],"Which day do you prefer, Friday or Sunday?"
761,2015-10-23 18:58:30.150,31,No,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Flattery,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,DESPAIR,DESPAIR,Sunday
762,2015-10-23 19:02:51.717,45,No,DESPAIR,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Laziness,2,2,3 or higher,3 or higher,3 or higher,3 or higher,JOY,DESPAIR,Friday
773,2015-10-23 19:14:25.765,39,No,DESPAIR,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,DESPAIR,DESPAIR,Friday
791,2015-10-23 19:31:58.588,37 (I'm taking a child),Yes,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Laziness,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,JOY,JOY,Sunday
825,2015-10-23 20:12:50.525,47,No,JOY,JOY,DESPAIR,JOY,JOY,JOY,JOY,...,Lazily flattering someone,3 or higher,2,3 or higher,3 or higher,2,1,DESPAIR,JOY,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5488,2015-10-30 08:09:36.131,44,No,JOY,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,1,DESPAIR,DESPAIR,Friday
5489,2015-10-30 08:12:02.094,66,No,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Lazily flattering someone,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,1,DESPAIR,DESPAIR,Friday
5547,2015-10-30 11:48:35.459,50,Yes,DESPAIR,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,...,Lazily flattering someone,3 or higher,3 or higher,2,3 or higher,3 or higher,2,DESPAIR,DESPAIR,Friday
5586,2015-10-30 15:39:39.356,Old,No,JOY,JOY,JOY,JOY,JOY,JOY,JOY,...,Lazily flattering someone,2,1,1,3 or higher,1,1,JOY,JOY,Friday
5628,2015-10-31 06:26:52.566,38,No,JOY,JOY,JOY,JOY,JOY,JOY,JOY,...,Lazily flattering someone,2,1,3 or higher,3 or higher,1,3 or higher,JOY,JOY,Sunday

### 2. Fill in missing values

In [384]:
# before fill in the missing age
df.iloc[36,1]

nan

In [385]:
# the age column has missing values, replace the missing age with the previous known number
age = df.iloc[:,1]
age = age.fillna(method='ffill')
age

0       35
1       41
2       33
3       31
4       30
        ..
5625    50
5626    43
5627    35
5628    38
5629    44
Name: How old are you?, Length: 5630, dtype: object

In [386]:
# after fill in the missing age
age[36]

60

### 3. Hierarchical Indexing

In [387]:
# partial indexing
df['Timestamp']

0      2015-10-23 08:46:20.451
1      2015-10-23 08:46:51.583
2      2015-10-23 08:47:34.285
3      2015-10-23 08:47:58.964
4      2015-10-23 08:48:11.719
                 ...
5625   2015-10-31 05:23:40.526
5626   2015-10-31 05:29:26.937
5627   2015-10-31 06:13:29.083
5628   2015-10-31 06:26:52.566
5629   2015-10-31 06:41:31.904
Name: Timestamp, Length: 5630, dtype: datetime64[ns]

In [388]:
# selection from inner level
df[['How old are you?', 'Are you going actually going trick or treating yourself?']].loc[10]

How old are you?                                            40
Are you going actually going trick or treating yourself?    No
Name: 10, dtype: object

In [389]:
# using unstack()
df[['How old are you?', 'Are you going actually going trick or treating yourself?']].unstack()

How old are you?                                          0        35
                                                          1        41
                                                          2        33
                                                          3        31
                                                          4        30
                                                                 ...
Are you going actually going trick or treating yourself?  5625     No
                                                          5626     No
                                                          5627    Yes
                                                          5628     No
                                                          5629     No
Length: 11260, dtype: object

### 4. Reshape

In [390]:
# rearrange the data with stack()
result = df.stack()
result

0     Timestamp                                                                                                            2015-10-23 08:46:20.451000
      How old are you?                                                                                                                             35
      Are you going actually going trick or treating yourself?                                                                                     No
       [Butterfinger]                                                                                                                             JOY
       [Anonymous brown globs that come in black and orange wrappers]                                                                         DESPAIR
                                                                                                                                      ...
5629  Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]                                   3 or higher
      Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]                   3 or higher
       [Sea-salt flavored stuff, probably chocolate, since this is the "it" flavor of the year]                                               DESPAIR
       [Necco Wafers]                                                                                                                             JOY
      Which day do you prefer, Friday or Sunday?                                                                                               Friday
Length: 570361, dtype: object

### 5. Groupby Mechanics

In [391]:
df = df_1
df.columns

Index(['Timestamp', 'How old are you?',
       'Are you going actually going trick or treating yourself?',
       ' [Butterfinger]', ' [100 Grand Bar]',
       ' [Anonymous brown globs that come in black and orange wrappers]',
       ' [Any full-sized candy bar]', ' [Black Jacks]', ' [Bonkers]',
       ' [Bottle Caps]',
       ...
       'Fill in the blank: "Imitation is a form of ____________"',
       'Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling]',
       'Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Bieber]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon]',
       'Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)]',
       ' [Sea-salt flavored stuff, probably chocolate, since this is the "it" flavor of the year]',
       ' [Necco Wafers]', 'Which day do you prefer, Friday or Sunday?'],
      dtype='object', length=115)

In [392]:
# combine the age column with the "Friday or Sunday" column 
grouped = df['How old are you?'].groupby(df['Which day do you prefer, Friday or Sunday?'])
grouped

In [393]:
grouped.describe()

                                            count  unique  top  freq
Which day do you prefer, Friday or Sunday?
Friday                                        153      47   30    12
Sunday                                         61      30   30     7

### More people prefer Friday over Sunday

### 6. Cross Tabs

In [394]:
# select age and day
age = df['How old are you?']
day = df['Which day do you prefer, Friday or Sunday?']

In [395]:
# perform cross tab to check the frequency
pd.crosstab(age, day, margins=True)

Which day do you prefer, Friday or Sunday?  Friday  Sunday  All
How old are you?
11                                               1       1    2
12                                               1       0    1
13                                               2       0    2
14                                               1       1    2
15                                               2       0    2
17                                               2       0    2
19                                               3       0    3
20                                               1       0    1
21                                               2       0    2
22                                               4       0    4
23                                               8       0    8
24                                               6       3    9
25                                               3       1    4
26                                               4       1    5
27                                               5       3    8
28                                               6       1    7
29                                               5       1    6
30                                              12       7   19
31                                               6       4   10
32                                               6       0    6
33                                               7       5   12
34                                               2       2    4
35                                               4       3    7
36                                               3       0    3
37                                               7       0    7
38                                               3       4    7
39                                               5       0    5
40                                               2       2    4
42                                               1       4    5
43                                               2       0    2
44                                               8       0    8
45                                               6       1    7
46                                               0       2    2
47                                               0       4    4
48                                               3       1    4
49                                               1       0    1
50                                               2       1    3
51                                               4       1    5
52                                               3       1    4
53                                               0       1    1
54                                               1       1    2
56                                               0       1    1
57                                               1       1    2
58                                               1       0    1
59                                               1       0    1
61                                               1       0    1
65                                               1       0    1
66                                               1       0    1
67                                               0       1    1
120                                              0       1    1
200587                                           1       0    1
37 (I'm taking a child)                          0       1    1
Enough                                           1       0    1
Old                                              1       0    1
All                                            153      61  214

### 7. Generate date range

In [413]:
# convert datetime64 to string
ts = df['Timestamp']
ts

761    2015-10-23 18:58:30.150
762    2015-10-23 19:02:51.717
773    2015-10-23 19:14:25.765
791    2015-10-23 19:31:58.588
825    2015-10-23 20:12:50.525
                 ...
5488   2015-10-30 08:09:36.131
5489   2015-10-30 08:12:02.094
5547   2015-10-30 11:48:35.459
5586   2015-10-30 15:39:39.356
5628   2015-10-31 06:26:52.566
Name: Timestamp, Length: 214, dtype: datetime64[ns]

In [418]:
index = pd.date_range(start='2015-10-01', periods=31)
index

DatetimeIndex(['2015-10-01', '2015-10-02', '2015-10-03', '2015-10-04',
               '2015-10-05', '2015-10-06', '2015-10-07', '2015-10-08',
               '2015-10-09', '2015-10-10', '2015-10-11', '2015-10-12',
               '2015-10-13', '2015-10-14', '2015-10-15', '2015-10-16',
               '2015-10-17', '2015-10-18', '2015-10-19', '2015-10-20',
               '2015-10-21', '2015-10-22', '2015-10-23', '2015-10-24',
               '2015-10-25', '2015-10-26', '2015-10-27', '2015-10-28',
               '2015-10-29', '2015-10-30', '2015-10-31'],
              dtype='datetime64[ns]', freq='D')

### 8. Period Frequency Conversion

In [428]:
# convert period to frequency using asfreq()
ts.asfreq('D', how='start')

1970-01-01 00:00:00.000000761   NaT
Freq: D, Name: Timestamp, dtype: datetime64[ns]

In [429]:
ts.asfreq('D', how='end')

1970-01-01 00:00:00.000000761   NaT
Freq: B, Name: Timestamp, dtype: datetime64[ns]